// Static samples referenced from https://www.badatime.com/67/spots.
// Coordinates identify the listed spots, not permitted access or safe fishing areas.
const fishingSpots = [
  {
    id: 1,
    name: "제주항 방파제",
    region: "제주도 북부",
    latitude: 33.53277778,
    longitude: 126.5408611,
    type: "방파제",
    fish: ["참돔", "벵에돔"],
    description: "제주항 북쪽 방파제의 빨간 등대 부근을 표시한 샘플 포인트입니다.",
    source: "바다타임",
  },
  {
    id: 2,
    name: "도두항 방파제",
    region: "제주도 북서부",
    latitude: 33.50972222,
    longitude: 126.4645278,
    type: "방파제",
    fish: ["감성돔", "벵에돔"],
    description: "제주시 도두항 방파제 부근을 표시한 샘플 포인트입니다.",
    source: "바다타임",
  },
  {
    id: 3,
    name: "이호등대 방파제",
    region: "제주도 북서부",
    latitude: 33.50186111,
    longitude: 126.4518889,
    type: "방파제",
    fish: ["농어", "감성돔"],
    description: "이호 해안의 등대 방파제 부근을 표시한 샘플 포인트입니다.",
    source: "바다타임",
  },
  {
    id: 4,
    name: "애월항 방파제",
    region: "제주도 북서부",
    latitude: 33.46897222,
    longitude: 126.3264444,
    type: "방파제",
    fish: ["감성돔", "벵에돔"],
    description: "애월항 방파제 부근을 표시한 샘플 포인트입니다.",
    source: "바다타임",
  },
  {
    id: 5,
    name: "김녕항 방파제",
    region: "제주도 북부",
    latitude: 33.56097222,
    longitude: 126.7404167,
    type: "방파제",
    fish: ["참돔", "한치"],
    description: "구좌읍 김녕항 방파제 부근을 표시한 샘플 포인트입니다.",
    source: "바다타임",
  },
  {
    id: 6,
    name: "세화항 방파제",
    region: "제주도 북동부",
    latitude: 33.52991667,
    longitude: 126.8583889,
    type: "방파제",
    fish: ["벵에돔", "무늬오징어"],
    description: "세화항 방파제 부근을 표시한 샘플 포인트입니다.",
    source: "바다타임",
  },
  {
    id: 7,
    name: "한림항",
    region: "제주도 서부",
    latitude: 33.41366667,
    longitude: 126.2536111,
    type: "방파제",
    fish: ["감성돔", "벵에돔"],
    description: "한림항 외측 방파제 부근을 표시한 샘플 포인트입니다.",
    source: "바다타임",
  },
  {
    id: 8,
    name: "위미항 방파제",
    region: "제주도 남동부",
    latitude: 33.26872222,
    longitude: 126.6606667,
    type: "방파제",
    fish: ["벵에돔", "돌돔"],
    description: "남원읍 위미항 방파제 부근을 표시한 샘플 포인트입니다.",
    source: "바다타임",
  },
  {
    id: 9,
    name: "서귀포항 방파제",
    region: "제주도 남부",
    latitude: 33.23580556,
    longitude: 126.5709444,
    type: "방파제",
    fish: ["벵에돔", "한치"],
    description: "서귀포항 방파제 부근을 표시한 샘플 포인트입니다.",
    source: "바다타임",
  },
  {
    id: 10,
    name: "법환포구 방파제",
    region: "제주도 남부",
    latitude: 33.23638889,
    longitude: 126.5166667,
    type: "방파제",
    fish: ["벵에돔", "우럭"],
    description: "법환포구 방파제 부근을 표시한 샘플 포인트입니다.",
    source: "바다타임",
  },
];
